//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public string RFC { get; set; }
        public string NombreCompleto { get; set; }
        public string Contrasenia { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Rol { get; set; }
        public string Clave_Escuela { get; set; }
    
        public virtual Escuela Escuela { get; set; }
    }
}
