//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baja
    {
        public string ID { get; set; }
        public string Motivo { get; set; }
        public byte[] DocumentoProbatorio { get; set; }
        public string Descripcion { get; set; }
        public string ID_Persona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
