//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion_Parcial
    {
        public string ID_Calificacion_Parcial { get; set; }
        public string ID_Cali { get; set; }
        public decimal CaliParcial { get; set; }
    
        public virtual Calificacion Calificacion { get; set; }
    }
}
