//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.Calificacions = new HashSet<Calificacion>();
        }
    
        public string Matricula { get; set; }
        public string NumSeguroSocial { get; set; }
        public byte[] DocCurpTutor { get; set; }
        public byte[] DocCertificadoSecundaria { get; set; }
        public byte[] DocCartaBuenaConducta { get; set; }
        public string ID_Persona { get; set; }
        public string ID_Grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacions { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
