//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Salon
    {
        public string ID_Grupo_Salon { get; set; }
        public string ID_Grupo { get; set; }
        public string Codigo_Salon { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
