//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia_Sesion
    {
        public string ID_Materia_Sesion { get; set; }
        public string ID_Profesor_Materia { get; set; }
        public string ID_Sesion { get; set; }
    
        public virtual Profesor_Materia Profesor_Materia { get; set; }
        public virtual Sesion Sesion { get; set; }
    }
}
