//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoEscolar_Semestre
    {
        public string ID_Periodo_Semestre { get; set; }
        public string ID_PeriodoEscolar { get; set; }
        public string Semestre { get; set; }
    
        public virtual PeriodoEscolar PeriodoEscolar { get; set; }
    }
}
