//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoEscolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodoEscolar()
        {
            this.PeriodoEscolar_Semestre = new HashSet<PeriodoEscolar_Semestre>();
        }
    
        public string ID { get; set; }
        public int AnioFinal { get; set; }
        public int AnioInicio { get; set; }
        public int MesFinal { get; set; }
        public int MesInicio { get; set; }
        public string Clave_Escuela { get; set; }
    
        public virtual Escuela Escuela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodoEscolar_Semestre> PeriodoEscolar_Semestre { get; set; }
    }
}
