//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor_Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor_Materia()
        {
            this.Materia_Sesion = new HashSet<Materia_Sesion>();
        }
    
        public string ID_Profesor_Materia { get; set; }
        public string RFC_Profesor { get; set; }
        public string NRC_Materia { get; set; }
    
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materia_Sesion> Materia_Sesion { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
