//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGHContext : DbContext
    {
        public SGHContext()
            : base("name=SGHContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Baja> Bajas { get; set; }
        public virtual DbSet<Calificacion> Calificacions { get; set; }
        public virtual DbSet<Calificacion_Parcial> Calificacion_Parcial { get; set; }
        public virtual DbSet<Escuela> Escuelas { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<Grupo_Salon> Grupo_Salon { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Materia_Sesion> Materia_Sesion { get; set; }
        public virtual DbSet<PeriodoEscolar> PeriodoEscolars { get; set; }
        public virtual DbSet<PeriodoEscolar_Semestre> PeriodoEscolar_Semestre { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Profesor_Materia> Profesor_Materia { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Sesion> Sesions { get; set; }
    }
}
