//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorSGH.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor_Materia
    {
        public string ID_Profesor_Materia { get; set; }
        public string RFC_Profesor { get; set; }
        public string NRC_Materia { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
