//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.ServiceReferenceSGH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrador", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Administrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Clave_EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Escuela EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave_Escuela {
            get {
                return this.Clave_EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.Clave_EscuelaField, value) != true)) {
                    this.Clave_EscuelaField = value;
                    this.RaisePropertyChanged("Clave_Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Escuela Escuela {
            get {
                return this.EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.EscuelaField, value) != true)) {
                    this.EscuelaField = value;
                    this.RaisePropertyChanged("Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Escuela", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Escuela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Administrador[] AdministradorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.PeriodoEscolar[] PeriodoEscolarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Administrador[] Administradors {
            get {
                return this.AdministradorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorsField, value) != true)) {
                    this.AdministradorsField = value;
                    this.RaisePropertyChanged("Administradors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.PeriodoEscolar[] PeriodoEscolars {
            get {
                return this.PeriodoEscolarsField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodoEscolarsField, value) != true)) {
                    this.PeriodoEscolarsField = value;
                    this.RaisePropertyChanged("PeriodoEscolars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolar", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class PeriodoEscolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Clave_EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Escuela EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.PeriodoEscolar_Semestre[] PeriodoEscolar_SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioFinal {
            get {
                return this.AnioFinalField;
            }
            set {
                if ((this.AnioFinalField.Equals(value) != true)) {
                    this.AnioFinalField = value;
                    this.RaisePropertyChanged("AnioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioInicio {
            get {
                return this.AnioInicioField;
            }
            set {
                if ((this.AnioInicioField.Equals(value) != true)) {
                    this.AnioInicioField = value;
                    this.RaisePropertyChanged("AnioInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave_Escuela {
            get {
                return this.Clave_EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.Clave_EscuelaField, value) != true)) {
                    this.Clave_EscuelaField = value;
                    this.RaisePropertyChanged("Clave_Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Escuela Escuela {
            get {
                return this.EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.EscuelaField, value) != true)) {
                    this.EscuelaField = value;
                    this.RaisePropertyChanged("Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesFinal {
            get {
                return this.MesFinalField;
            }
            set {
                if ((this.MesFinalField.Equals(value) != true)) {
                    this.MesFinalField = value;
                    this.RaisePropertyChanged("MesFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesInicio {
            get {
                return this.MesInicioField;
            }
            set {
                if ((this.MesInicioField.Equals(value) != true)) {
                    this.MesInicioField = value;
                    this.RaisePropertyChanged("MesInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.PeriodoEscolar_Semestre[] PeriodoEscolar_Semestre {
            get {
                return this.PeriodoEscolar_SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodoEscolar_SemestreField, value) != true)) {
                    this.PeriodoEscolar_SemestreField = value;
                    this.RaisePropertyChanged("PeriodoEscolar_Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ActaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Baja[] BajasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Clave_EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocCurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Escuela EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Estudiante[] EstudiantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Profesor[] ProfesorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSangreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ActaNacimiento {
            get {
                return this.ActaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActaNacimientoField, value) != true)) {
                    this.ActaNacimientoField = value;
                    this.RaisePropertyChanged("ActaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Baja[] Bajas {
            get {
                return this.BajasField;
            }
            set {
                if ((object.ReferenceEquals(this.BajasField, value) != true)) {
                    this.BajasField = value;
                    this.RaisePropertyChanged("Bajas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave_Escuela {
            get {
                return this.Clave_EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.Clave_EscuelaField, value) != true)) {
                    this.Clave_EscuelaField = value;
                    this.RaisePropertyChanged("Clave_Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocCurp {
            get {
                return this.DocCurpField;
            }
            set {
                if ((object.ReferenceEquals(this.DocCurpField, value) != true)) {
                    this.DocCurpField = value;
                    this.RaisePropertyChanged("DocCurp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Escuela Escuela {
            get {
                return this.EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.EscuelaField, value) != true)) {
                    this.EscuelaField = value;
                    this.RaisePropertyChanged("Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Estudiante[] Estudiantes {
            get {
                return this.EstudiantesField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudiantesField, value) != true)) {
                    this.EstudiantesField = value;
                    this.RaisePropertyChanged("Estudiantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Profesor[] Profesors {
            get {
                return this.ProfesorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorsField, value) != true)) {
                    this.ProfesorsField = value;
                    this.RaisePropertyChanged("Profesors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSangre {
            get {
                return this.TipoSangreField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSangreField, value) != true)) {
                    this.TipoSangreField = value;
                    this.RaisePropertyChanged("TipoSangre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolar_Semestre", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class PeriodoEscolar_Semestre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_PeriodoEscolarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Periodo_SemestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.PeriodoEscolar PeriodoEscolarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PeriodoEscolar {
            get {
                return this.ID_PeriodoEscolarField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_PeriodoEscolarField, value) != true)) {
                    this.ID_PeriodoEscolarField = value;
                    this.RaisePropertyChanged("ID_PeriodoEscolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Periodo_Semestre {
            get {
                return this.ID_Periodo_SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Periodo_SemestreField, value) != true)) {
                    this.ID_Periodo_SemestreField = value;
                    this.RaisePropertyChanged("ID_Periodo_Semestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.PeriodoEscolar PeriodoEscolar {
            get {
                return this.PeriodoEscolarField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodoEscolarField, value) != true)) {
                    this.PeriodoEscolarField = value;
                    this.RaisePropertyChanged("PeriodoEscolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Baja", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Baja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentoProbatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Persona PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentoProbatorio {
            get {
                return this.DocumentoProbatorioField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoProbatorioField, value) != true)) {
                    this.DocumentoProbatorioField = value;
                    this.RaisePropertyChanged("DocumentoProbatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Persona {
            get {
                return this.ID_PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_PersonaField, value) != true)) {
                    this.ID_PersonaField = value;
                    this.RaisePropertyChanged("ID_Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Calificacion[] CalificacionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocCartaBuenaConductaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocCertificadoSecundariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocCurpTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Grupo GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumSeguroSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Persona PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Calificacion[] Calificacions {
            get {
                return this.CalificacionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CalificacionsField, value) != true)) {
                    this.CalificacionsField = value;
                    this.RaisePropertyChanged("Calificacions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocCartaBuenaConducta {
            get {
                return this.DocCartaBuenaConductaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocCartaBuenaConductaField, value) != true)) {
                    this.DocCartaBuenaConductaField = value;
                    this.RaisePropertyChanged("DocCartaBuenaConducta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocCertificadoSecundaria {
            get {
                return this.DocCertificadoSecundariaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocCertificadoSecundariaField, value) != true)) {
                    this.DocCertificadoSecundariaField = value;
                    this.RaisePropertyChanged("DocCertificadoSecundaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocCurpTutor {
            get {
                return this.DocCurpTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.DocCurpTutorField, value) != true)) {
                    this.DocCurpTutorField = value;
                    this.RaisePropertyChanged("DocCurpTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Grupo Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Grupo {
            get {
                return this.ID_GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GrupoField, value) != true)) {
                    this.ID_GrupoField = value;
                    this.RaisePropertyChanged("ID_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Persona {
            get {
                return this.ID_PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_PersonaField, value) != true)) {
                    this.ID_PersonaField = value;
                    this.RaisePropertyChanged("ID_Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSeguroSocial {
            get {
                return this.NumSeguroSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.NumSeguroSocialField, value) != true)) {
                    this.NumSeguroSocialField = value;
                    this.RaisePropertyChanged("NumSeguroSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesor", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Profesor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] INEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Persona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Profesor_Materia[] Profesor_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocContrato {
            get {
                return this.DocContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocContratoField, value) != true)) {
                    this.DocContratoField = value;
                    this.RaisePropertyChanged("DocContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Persona {
            get {
                return this.ID_PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_PersonaField, value) != true)) {
                    this.ID_PersonaField = value;
                    this.RaisePropertyChanged("ID_Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] INE {
            get {
                return this.INEField;
            }
            set {
                if ((object.ReferenceEquals(this.INEField, value) != true)) {
                    this.INEField = value;
                    this.RaisePropertyChanged("INE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Profesor_Materia[] Profesor_Materia {
            get {
                return this.Profesor_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Profesor_MateriaField, value) != true)) {
                    this.Profesor_MateriaField = value;
                    this.RaisePropertyChanged("Profesor_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Grupo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Estudiante[] EstudiantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Grupo_Salon[] Grupo_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SemestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Sesion[] SesionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Estudiante[] Estudiantes {
            get {
                return this.EstudiantesField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudiantesField, value) != true)) {
                    this.EstudiantesField = value;
                    this.RaisePropertyChanged("Estudiantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Grupo_Salon[] Grupo_Salon {
            get {
                return this.Grupo_SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.Grupo_SalonField, value) != true)) {
                    this.Grupo_SalonField = value;
                    this.RaisePropertyChanged("Grupo_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letra {
            get {
                return this.LetraField;
            }
            set {
                if ((object.ReferenceEquals(this.LetraField, value) != true)) {
                    this.LetraField = value;
                    this.RaisePropertyChanged("Letra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((this.SemestreField.Equals(value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Sesion[] Sesions {
            get {
                return this.SesionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionsField, value) != true)) {
                    this.SesionsField = value;
                    this.RaisePropertyChanged("Sesions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calificacion", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Calificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Calificacion_Parcial[] Calificacion_ParcialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadParcialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Estudiante EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EvalFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Materia MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Matricula_EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRC_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PromedioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PromedioParcialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Calificacion_Parcial[] Calificacion_Parcial {
            get {
                return this.Calificacion_ParcialField;
            }
            set {
                if ((object.ReferenceEquals(this.Calificacion_ParcialField, value) != true)) {
                    this.Calificacion_ParcialField = value;
                    this.RaisePropertyChanged("Calificacion_Parcial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadParciales {
            get {
                return this.CantidadParcialesField;
            }
            set {
                if ((this.CantidadParcialesField.Equals(value) != true)) {
                    this.CantidadParcialesField = value;
                    this.RaisePropertyChanged("CantidadParciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Estudiante Estudiante {
            get {
                return this.EstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstudianteField, value) != true)) {
                    this.EstudianteField = value;
                    this.RaisePropertyChanged("Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EvalFinal {
            get {
                return this.EvalFinalField;
            }
            set {
                if ((this.EvalFinalField.Equals(value) != true)) {
                    this.EvalFinalField = value;
                    this.RaisePropertyChanged("EvalFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Materia Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula_Estudiante {
            get {
                return this.Matricula_EstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.Matricula_EstudianteField, value) != true)) {
                    this.Matricula_EstudianteField = value;
                    this.RaisePropertyChanged("Matricula_Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRC_Materia {
            get {
                return this.NRC_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NRC_MateriaField, value) != true)) {
                    this.NRC_MateriaField = value;
                    this.RaisePropertyChanged("NRC_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioFinal {
            get {
                return this.PromedioFinalField;
            }
            set {
                if ((this.PromedioFinalField.Equals(value) != true)) {
                    this.PromedioFinalField = value;
                    this.RaisePropertyChanged("PromedioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PromedioParcial {
            get {
                return this.PromedioParcialField;
            }
            set {
                if ((this.PromedioParcialField.Equals(value) != true)) {
                    this.PromedioParcialField = value;
                    this.RaisePropertyChanged("PromedioParcial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Materia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Calificacion[] CalificacionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Materia_Sesion[] Materia_SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSesionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Profesor_Materia[] Profesor_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SemestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Calificacion[] Calificacions {
            get {
                return this.CalificacionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CalificacionsField, value) != true)) {
                    this.CalificacionsField = value;
                    this.RaisePropertyChanged("Calificacions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Materia_Sesion[] Materia_Sesion {
            get {
                return this.Materia_SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.Materia_SesionField, value) != true)) {
                    this.Materia_SesionField = value;
                    this.RaisePropertyChanged("Materia_Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRC {
            get {
                return this.NRCField;
            }
            set {
                if ((object.ReferenceEquals(this.NRCField, value) != true)) {
                    this.NRCField = value;
                    this.RaisePropertyChanged("NRC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSesiones {
            get {
                return this.NumSesionesField;
            }
            set {
                if ((this.NumSesionesField.Equals(value) != true)) {
                    this.NumSesionesField = value;
                    this.RaisePropertyChanged("NumSesiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Profesor_Materia[] Profesor_Materia {
            get {
                return this.Profesor_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Profesor_MateriaField, value) != true)) {
                    this.Profesor_MateriaField = value;
                    this.RaisePropertyChanged("Profesor_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((this.SemestreField.Equals(value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calificacion_Parcial", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Calificacion_Parcial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CaliParcialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Calificacion CalificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_CaliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Calificacion_ParcialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CaliParcial {
            get {
                return this.CaliParcialField;
            }
            set {
                if ((this.CaliParcialField.Equals(value) != true)) {
                    this.CaliParcialField = value;
                    this.RaisePropertyChanged("CaliParcial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Calificacion Calificacion {
            get {
                return this.CalificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CalificacionField, value) != true)) {
                    this.CalificacionField = value;
                    this.RaisePropertyChanged("Calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Cali {
            get {
                return this.ID_CaliField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_CaliField, value) != true)) {
                    this.ID_CaliField = value;
                    this.RaisePropertyChanged("ID_Cali");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Calificacion_Parcial {
            get {
                return this.ID_Calificacion_ParcialField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Calificacion_ParcialField, value) != true)) {
                    this.ID_Calificacion_ParcialField = value;
                    this.RaisePropertyChanged("ID_Calificacion_Parcial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia_Sesion", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Materia_Sesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Materia_SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Materia MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRC_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Sesion SesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Materia_Sesion {
            get {
                return this.ID_Materia_SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Materia_SesionField, value) != true)) {
                    this.ID_Materia_SesionField = value;
                    this.RaisePropertyChanged("ID_Materia_Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Sesion {
            get {
                return this.ID_SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_SesionField, value) != true)) {
                    this.ID_SesionField = value;
                    this.RaisePropertyChanged("ID_Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Materia Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRC_Materia {
            get {
                return this.NRC_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NRC_MateriaField, value) != true)) {
                    this.NRC_MateriaField = value;
                    this.RaisePropertyChanged("NRC_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Sesion Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionField, value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesor_Materia", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Profesor_Materia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Profesor_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Materia MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRC_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Profesor ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFC_ProfesorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Profesor_Materia {
            get {
                return this.ID_Profesor_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Profesor_MateriaField, value) != true)) {
                    this.ID_Profesor_MateriaField = value;
                    this.RaisePropertyChanged("ID_Profesor_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Materia Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRC_Materia {
            get {
                return this.NRC_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NRC_MateriaField, value) != true)) {
                    this.NRC_MateriaField = value;
                    this.RaisePropertyChanged("NRC_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Profesor Profesor {
            get {
                return this.ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesorField, value) != true)) {
                    this.ProfesorField = value;
                    this.RaisePropertyChanged("Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC_Profesor {
            get {
                return this.RFC_ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFC_ProfesorField, value) != true)) {
                    this.RFC_ProfesorField = value;
                    this.RaisePropertyChanged("RFC_Profesor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sesion", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Sesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaSemanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Grupo GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Materia_Sesion[] Materia_SesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaSemana {
            get {
                return this.DiaSemanaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaSemanaField, value) != true)) {
                    this.DiaSemanaField = value;
                    this.RaisePropertyChanged("DiaSemana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Grupo Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFinal {
            get {
                return this.HoraFinalField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinalField, value) != true)) {
                    this.HoraFinalField = value;
                    this.RaisePropertyChanged("HoraFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Grupo {
            get {
                return this.ID_GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GrupoField, value) != true)) {
                    this.ID_GrupoField = value;
                    this.RaisePropertyChanged("ID_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Materia_Sesion[] Materia_Sesion {
            get {
                return this.Materia_SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.Materia_SesionField, value) != true)) {
                    this.Materia_SesionField = value;
                    this.RaisePropertyChanged("Materia_Sesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo_Salon", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Grupo_Salon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Grupo GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_Grupo_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Salon SalonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_Salon {
            get {
                return this.Codigo_SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_SalonField, value) != true)) {
                    this.Codigo_SalonField = value;
                    this.RaisePropertyChanged("Codigo_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Grupo Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Grupo {
            get {
                return this.ID_GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GrupoField, value) != true)) {
                    this.ID_GrupoField = value;
                    this.RaisePropertyChanged("ID_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Grupo_Salon {
            get {
                return this.ID_Grupo_SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_Grupo_SalonField, value) != true)) {
                    this.ID_Grupo_SalonField = value;
                    this.RaisePropertyChanged("ID_Grupo_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Salon Salon {
            get {
                return this.SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.SalonField, value) != true)) {
                    this.SalonField = value;
                    this.RaisePropertyChanged("Salon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salon", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH.Modelos")]
    [System.SerializableAttribute()]
    public partial class Salon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGH.ServiceReferenceSGH.Grupo_Salon[] Grupo_SalonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cupo {
            get {
                return this.CupoField;
            }
            set {
                if ((this.CupoField.Equals(value) != true)) {
                    this.CupoField = value;
                    this.RaisePropertyChanged("Cupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGH.ServiceReferenceSGH.Grupo_Salon[] Grupo_Salon {
            get {
                return this.Grupo_SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.Grupo_SalonField, value) != true)) {
                    this.Grupo_SalonField = value;
                    this.RaisePropertyChanged("Grupo_Salon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSGH.IServiceSGH")]
    public interface IServiceSGH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetData", ReplyAction="http://tempuri.org/IServiceSGH/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetData", ReplyAction="http://tempuri.org/IServiceSGH/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSGH/GetDataUsingDataContractResponse")]
        SGH.ServiceReferenceSGH.CompositeType GetDataUsingDataContract(SGH.ServiceReferenceSGH.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSGH/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.CompositeType> GetDataUsingDataContractAsync(SGH.ServiceReferenceSGH.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetRFCUsuario", ReplyAction="http://tempuri.org/IServiceSGH/GetRFCUsuarioResponse")]
        string GetRFCUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetRFCUsuario", ReplyAction="http://tempuri.org/IServiceSGH/GetRFCUsuarioResponse")]
        System.Threading.Tasks.Task<string> GetRFCUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/ExisteUsuario", ReplyAction="http://tempuri.org/IServiceSGH/ExisteUsuarioResponse")]
        SGH.ServiceReferenceSGH.Administrador ExisteUsuario(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/ExisteUsuario", ReplyAction="http://tempuri.org/IServiceSGH/ExisteUsuarioResponse")]
        System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.Administrador> ExisteUsuarioAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSGHChannel : SGH.ServiceReferenceSGH.IServiceSGH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSGHClient : System.ServiceModel.ClientBase<SGH.ServiceReferenceSGH.IServiceSGH>, SGH.ServiceReferenceSGH.IServiceSGH {
        
        public ServiceSGHClient() {
        }
        
        public ServiceSGHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSGHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSGHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSGHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SGH.ServiceReferenceSGH.CompositeType GetDataUsingDataContract(SGH.ServiceReferenceSGH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.CompositeType> GetDataUsingDataContractAsync(SGH.ServiceReferenceSGH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetRFCUsuario() {
            return base.Channel.GetRFCUsuario();
        }
        
        public System.Threading.Tasks.Task<string> GetRFCUsuarioAsync() {
            return base.Channel.GetRFCUsuarioAsync();
        }
        
        public SGH.ServiceReferenceSGH.Administrador ExisteUsuario(string correo) {
            return base.Channel.ExisteUsuario(correo);
        }
        
        public System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.Administrador> ExisteUsuarioAsync(string correo) {
            return base.Channel.ExisteUsuarioAsync(correo);
        }
    }
}
