//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGH.ServiceReferenceSGH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServidorSGH")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSGH.IServiceSGH")]
    public interface IServiceSGH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetData", ReplyAction="http://tempuri.org/IServiceSGH/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetData", ReplyAction="http://tempuri.org/IServiceSGH/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSGH/GetDataUsingDataContractResponse")]
        SGH.ServiceReferenceSGH.CompositeType GetDataUsingDataContract(SGH.ServiceReferenceSGH.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSGH/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.CompositeType> GetDataUsingDataContractAsync(SGH.ServiceReferenceSGH.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetRFCUsuario", ReplyAction="http://tempuri.org/IServiceSGH/GetRFCUsuarioResponse")]
        string GetRFCUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/GetRFCUsuario", ReplyAction="http://tempuri.org/IServiceSGH/GetRFCUsuarioResponse")]
        System.Threading.Tasks.Task<string> GetRFCUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/ExisteUsuario", ReplyAction="http://tempuri.org/IServiceSGH/ExisteUsuarioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SGH.ServiceReferenceSGH.CompositeType))]
        object ExisteUsuario(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSGH/ExisteUsuario", ReplyAction="http://tempuri.org/IServiceSGH/ExisteUsuarioResponse")]
        System.Threading.Tasks.Task<object> ExisteUsuarioAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSGHChannel : SGH.ServiceReferenceSGH.IServiceSGH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSGHClient : System.ServiceModel.ClientBase<SGH.ServiceReferenceSGH.IServiceSGH>, SGH.ServiceReferenceSGH.IServiceSGH {
        
        public ServiceSGHClient() {
        }
        
        public ServiceSGHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSGHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSGHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSGHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SGH.ServiceReferenceSGH.CompositeType GetDataUsingDataContract(SGH.ServiceReferenceSGH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SGH.ServiceReferenceSGH.CompositeType> GetDataUsingDataContractAsync(SGH.ServiceReferenceSGH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetRFCUsuario() {
            return base.Channel.GetRFCUsuario();
        }
        
        public System.Threading.Tasks.Task<string> GetRFCUsuarioAsync() {
            return base.Channel.GetRFCUsuarioAsync();
        }
        
        public object ExisteUsuario(string correo) {
            return base.Channel.ExisteUsuario(correo);
        }
        
        public System.Threading.Tasks.Task<object> ExisteUsuarioAsync(string correo) {
            return base.Channel.ExisteUsuarioAsync(correo);
        }
    }
}
